### ISSUE TITLE
No check the default timezone is available

### ISSUE THREAD

**Issue by mudrd8mz** [moodlerooms/moodle-mod_collaborate#1]
In a rare case that the `date_default_timezone_get()` returns a timezone not available via `get_list_of_timezones()`, a notice like

```
Notice: Undefined index: Europe/Prague in ..../mod/collaborate/mod_form.php on line 85
```

appears and the form item label reads

```
Start (Timezone: {$a})
```

I am aware this is actually a result of a misconfigured site. Yet you might want to handle this unexpected case. Indeed, updating the timezone info from the admin UI fixes the problem.

**Comment by gthomas2** [comment]
Thank you for reporting this issue David. It has been fixed in the next release (out sometime October).
