### ISSUE TITLE
Collaborate Moodle 3.3 compability?

### ISSUE THREAD

**Issue by Jarvil** [moodlerooms/moodle-mod_collaborate#5]
Hello,

Do we get Moodle 3.3 compatible version of this plugin to download from https://moodle.org/plugins/

**Comment by Jarvil** [comment]
@Rabecerra

**Comment by Rabecerra** [comment]
Hi Jarvil, we just updated the plugin with 3.3 version, you can check it here. https://moodle.org/plugins/pluginversions.php?plugin=mod_collaborate

**Comment by Jarvil** [comment]
Hello,

Thank you very much.
